#!/usr/bin/env node
/**
 * Continue.dev Adapter Generator
 *
 * Reads aide agents/skills and generates Continue.dev config snippets.
 * Continue uses config.json with customCommands and contextProviders.
 *
 * Usage: npx ts-node adapters/continue/generate.ts [--output=path]
 */

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'fs';
import { join, basename } from 'path';

interface Agent {
  name: string;
  description: string;
  prompt: string;
  defaultModel?: string;
}

interface Skill {
  name: string;
  description: string;
  triggers: string[];
  content: string;
}

interface ContinueCommand {
  name: string;
  description: string;
  prompt: string;
}

const ROOT = join(__dirname, '..', '..');
const AGENTS_DIR = join(ROOT, 'src', 'agents');
const SKILLS_DIR = join(ROOT, 'src', 'skills');

/**
 * Parse YAML frontmatter from markdown
 */
function parseFrontmatter(content: string): { meta: Record<string, unknown>; body: string } | null {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return null;

  const yaml = match[1];
  const body = match[2].trim();
  const meta: Record<string, unknown> = {};

  // Simple YAML parsing
  const nameMatch = yaml.match(/^name:\s*(.+)$/m);
  if (nameMatch) meta.name = nameMatch[1].trim();

  const descMatch = yaml.match(/^description:\s*(.+)$/m);
  if (descMatch) meta.description = descMatch[1].trim();

  const modelMatch = yaml.match(/^defaultModel:\s*(.+)$/m);
  if (modelMatch) meta.defaultModel = modelMatch[1].trim();

  // Parse triggers array
  const triggers: string[] = [];
  const triggerMatch = yaml.match(/triggers:\s*\n((?:\s+-\s*.+\n?)*)/);
  if (triggerMatch) {
    const lines = triggerMatch[1].split('\n');
    for (const line of lines) {
      const itemMatch = line.match(/^\s+-\s*(.+)$/);
      if (itemMatch) triggers.push(itemMatch[1].trim());
    }
  }
  meta.triggers = triggers;

  return { meta, body };
}

/**
 * Load all agents
 */
function loadAgents(): Agent[] {
  if (!existsSync(AGENTS_DIR)) return [];

  const agents: Agent[] = [];
  const files = readdirSync(AGENTS_DIR).filter(f => f.endsWith('.md'));

  for (const file of files) {
    const content = readFileSync(join(AGENTS_DIR, file), 'utf-8');
    const parsed = parseFrontmatter(content);
    if (!parsed) continue;

    agents.push({
      name: (parsed.meta.name as string) || basename(file, '.md'),
      description: (parsed.meta.description as string) || '',
      defaultModel: parsed.meta.defaultModel as string | undefined,
      prompt: parsed.body,
    });
  }

  return agents;
}

/**
 * Load all skills
 */
function loadSkills(): Skill[] {
  if (!existsSync(SKILLS_DIR)) return [];

  const skills: Skill[] = [];
  const files = readdirSync(SKILLS_DIR).filter(f => f.endsWith('.md'));

  for (const file of files) {
    const content = readFileSync(join(SKILLS_DIR, file), 'utf-8');
    const parsed = parseFrontmatter(content);
    if (!parsed) continue;

    skills.push({
      name: (parsed.meta.name as string) || basename(file, '.md'),
      description: (parsed.meta.description as string) || '',
      triggers: (parsed.meta.triggers as string[]) || [],
      content: parsed.body,
    });
  }

  return skills;
}

/**
 * Convert aide model tier to Continue model
 */
function mapModel(tier?: string): string {
  switch (tier) {
    case 'fast': return 'claude-3-haiku';
    case 'balanced': return 'claude-3-5-sonnet';
    case 'smart': return 'claude-3-opus';
    default: return 'claude-3-5-sonnet';
  }
}

/**
 * Generate Continue.dev config snippet
 */
function generateConfig(agents: Agent[], skills: Skill[]): object {
  const customCommands: ContinueCommand[] = [];

  // Convert agents to slash commands
  for (const agent of agents) {
    customCommands.push({
      name: agent.name,
      description: agent.description || `Run ${agent.name} agent`,
      prompt: agent.prompt,
    });
  }

  // Convert skills to slash commands
  for (const skill of skills) {
    customCommands.push({
      name: skill.name,
      description: skill.description || `Activate ${skill.name} skill`,
      prompt: skill.content,
    });
  }

  return {
    _comment: 'Generated by aide - merge into your ~/.continue/config.json',
    customCommands,
  };
}

function main() {
  const args = process.argv.slice(2);
  const outputArg = args.find(a => a.startsWith('--output='));
  const outputPath = outputArg
    ? outputArg.split('=')[1]
    : join(__dirname, 'continue-config-snippet.json');

  console.log('Loading aide agents and skills...');
  const agents = loadAgents();
  const skills = loadSkills();

  console.log(`Found ${agents.length} agents and ${skills.length} skills`);

  const config = generateConfig(agents, skills);

  writeFileSync(outputPath, JSON.stringify(config, null, 2));
  console.log(`Generated Continue.dev config: ${outputPath}`);
  console.log('\nMerge customCommands into your ~/.continue/config.json');
}

main();
