package grammar

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"time"
)

const (
	// LockFileName is the name of the grammar lock file, stored at the project root.
	LockFileName = ".aide-grammars.lock"
)

// LockFile records pinned grammar versions for reproducible installs.
// It is intended to be committed to version control so all team members
// use the same grammar versions.
type LockFile struct {
	// Comment helps humans understand the file.
	Comment string `json:"_comment"`
	// GeneratedAt is when the lock file was last updated.
	GeneratedAt time.Time `json:"generated_at"`
	// Grammars maps language name to its pinned entry.
	Grammars map[string]*LockEntry `json:"grammars"`
}

// LockEntry pins a single grammar to a specific version and checksum.
type LockEntry struct {
	Version string `json:"version"`
	SHA256  string `json:"sha256"`
	CSymbol string `json:"c_symbol"`
}

// ReadLockFile reads a grammars lock file from disk.
// Returns nil (not an error) if the file does not exist.
func ReadLockFile(projectRoot string) (*LockFile, error) {
	path := filepath.Join(projectRoot, LockFileName)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}

	var lf LockFile
	if err := json.Unmarshal(data, &lf); err != nil {
		return nil, err
	}
	if lf.Grammars == nil {
		lf.Grammars = make(map[string]*LockEntry)
	}
	return &lf, nil
}

// WriteLockFile writes the lock file to the project root.
func WriteLockFile(projectRoot string, lf *LockFile) error {
	lf.Comment = "Auto-generated by aide grammar install. Commit this file to pin grammar versions."
	lf.GeneratedAt = time.Now().UTC()

	data, err := json.MarshalIndent(lf, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')

	return os.WriteFile(filepath.Join(projectRoot, LockFileName), data, 0o644)
}

// LockFileFromManifest generates a lock file from the current manifest state.
// Only dynamic (non-builtin) grammars are included.
func LockFileFromManifest(ms *manifestStore) *LockFile {
	entries := ms.entries()
	lf := &LockFile{
		Grammars: make(map[string]*LockEntry, len(entries)),
	}
	for name, me := range entries {
		lf.Grammars[name] = &LockEntry{
			Version: me.Version,
			SHA256:  me.SHA256,
			CSymbol: me.CSymbol,
		}
	}
	return lf
}

// Names returns sorted grammar names from the lock file.
func (lf *LockFile) Names() []string {
	names := make([]string, 0, len(lf.Grammars))
	for name := range lf.Grammars {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
