#!/usr/bin/env node
/**
 * Aider Adapter Generator
 *
 * Reads aide agents/skills and generates aider conventions file.
 * Aider uses .aider.conf.yml and CONVENTIONS.md for customization.
 *
 * Usage: npx ts-node adapters/aider/generate.ts [--output=path]
 */

import { readFileSync, readdirSync, writeFileSync, existsSync } from 'fs';
import { join, basename } from 'path';

interface Agent {
  name: string;
  description: string;
  prompt: string;
}

interface Skill {
  name: string;
  description: string;
  triggers: string[];
  content: string;
}

const ROOT = join(__dirname, '..', '..');
const AGENTS_DIR = join(ROOT, 'src', 'agents');
const SKILLS_DIR = join(ROOT, 'src', 'skills');

/**
 * Parse YAML frontmatter from markdown
 */
function parseFrontmatter(content: string): { meta: Record<string, unknown>; body: string } | null {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return null;

  const yaml = match[1];
  const body = match[2].trim();
  const meta: Record<string, unknown> = {};

  const nameMatch = yaml.match(/^name:\s*(.+)$/m);
  if (nameMatch) meta.name = nameMatch[1].trim();

  const descMatch = yaml.match(/^description:\s*(.+)$/m);
  if (descMatch) meta.description = descMatch[1].trim();

  const triggers: string[] = [];
  const triggerMatch = yaml.match(/triggers:\s*\n((?:\s+-\s*.+\n?)*)/);
  if (triggerMatch) {
    const lines = triggerMatch[1].split('\n');
    for (const line of lines) {
      const itemMatch = line.match(/^\s+-\s*(.+)$/);
      if (itemMatch) triggers.push(itemMatch[1].trim());
    }
  }
  meta.triggers = triggers;

  return { meta, body };
}

/**
 * Load all agents
 */
function loadAgents(): Agent[] {
  if (!existsSync(AGENTS_DIR)) return [];

  const agents: Agent[] = [];
  const files = readdirSync(AGENTS_DIR).filter(f => f.endsWith('.md'));

  for (const file of files) {
    const content = readFileSync(join(AGENTS_DIR, file), 'utf-8');
    const parsed = parseFrontmatter(content);
    if (!parsed) continue;

    agents.push({
      name: (parsed.meta.name as string) || basename(file, '.md'),
      description: (parsed.meta.description as string) || '',
      prompt: parsed.body,
    });
  }

  return agents;
}

/**
 * Load all skills
 */
function loadSkills(): Skill[] {
  if (!existsSync(SKILLS_DIR)) return [];

  const skills: Skill[] = [];
  const files = readdirSync(SKILLS_DIR).filter(f => f.endsWith('.md'));

  for (const file of files) {
    const content = readFileSync(join(SKILLS_DIR, file), 'utf-8');
    const parsed = parseFrontmatter(content);
    if (!parsed) continue;

    skills.push({
      name: (parsed.meta.name as string) || basename(file, '.md'),
      description: (parsed.meta.description as string) || '',
      triggers: (parsed.meta.triggers as string[]) || [],
      content: parsed.body,
    });
  }

  return skills;
}

/**
 * Generate CONVENTIONS.md for aider
 */
function generateConventions(agents: Agent[], skills: Skill[]): string {
  const lines: string[] = [
    '# AIDE Conventions',
    '',
    'This file is generated from aide agents and skills.',
    'It provides guidance for AI-assisted development.',
    '',
    '## Agent Behaviors',
    '',
    'Use these mental models when working on different task types:',
    '',
  ];

  for (const agent of agents) {
    lines.push(`### ${agent.name}`);
    if (agent.description) {
      lines.push(`> ${agent.description}`);
    }
    lines.push('');
    lines.push(agent.prompt);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('## Workflow Patterns');
  lines.push('');

  for (const skill of skills) {
    lines.push(`### ${skill.name}`);
    if (skill.description) {
      lines.push(`> ${skill.description}`);
    }
    if (skill.triggers.length > 0) {
      lines.push(`> Triggers: ${skill.triggers.join(', ')}`);
    }
    lines.push('');
    lines.push(skill.content);
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate .aider.conf.yml
 */
function generateAiderConfig(): string {
  return `# AIDE Aider Configuration
# Generated by aide adapter

# Read conventions file
read: CONVENTIONS.md

# Suggested model settings
# model: claude-3-5-sonnet-20241022

# Auto-commit settings
auto-commits: false
dirty-commits: false

# Context settings
map-tokens: 2048
`;
}

function main() {
  const args = process.argv.slice(2);
  const outputArg = args.find(a => a.startsWith('--output='));
  const outputDir = outputArg
    ? outputArg.split('=')[1]
    : __dirname;

  console.log('Loading aide agents and skills...');
  const agents = loadAgents();
  const skills = loadSkills();

  console.log(`Found ${agents.length} agents and ${skills.length} skills`);

  // Generate CONVENTIONS.md
  const conventions = generateConventions(agents, skills);
  const conventionsPath = join(outputDir, 'CONVENTIONS.md');
  writeFileSync(conventionsPath, conventions);
  console.log(`Generated: ${conventionsPath}`);

  // Generate .aider.conf.yml
  const config = generateAiderConfig();
  const configPath = join(outputDir, '.aider.conf.yml');
  writeFileSync(configPath, config);
  console.log(`Generated: ${configPath}`);

  console.log('\nCopy both files to your project root to use with aider');
}

main();
